package cli

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/viper"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/eraceo/Hako/internal/memory"
	"github.com/eraceo/Hako/internal/secrets"
	"github.com/eraceo/Hako/internal/storage"
)

type exportTestCase struct {
	name             string
	args             []string
	simulatedInput   string
	expectedContains []string
	expectedError    string
	verifyFile       bool // If true, verify the file generated by --out exists
	missingVault     bool // If true, forces the vault path to a non-existent file
}

func getExportCmdTestCases(testMasterPass string) []exportTestCase {
	return []exportTestCase{
		{
			name:           "Export JSON to stdout (forced)",
			args:           []string{"export", "--force", "--format=json"},
			simulatedInput: testMasterPass + "\n",
			expectedContains: []string{
				`"name": "AppA"`,
				`"username": "admin"`,
				`"password": "StandardPass123"`,
				// JSON escaping of special chars
				`"password": "P@ss\"word\nLine2"`,
			},
		},
		{
			name:           "Export CSV to stdout (forced)",
			args:           []string{"export", "--force", "--format=csv"},
			simulatedInput: testMasterPass + "\n",
			expectedContains: []string{
				"Name,Username,Password,URL,Notes,Tags,Created,Updated",
				"AppA,admin,StandardPass123,https://a.com,notes A,tag1,",
				// CSV escaping of quotes and commas
				`AppB,user_name,"P@ss""word`,
			},
		},
		{
			name: "Export interactive (cancel)",
			args: []string{"export", "--format=json"},
			// Master pass + 'n' to cancel confirmation prompt
			simulatedInput: testMasterPass + "\nn\n",
			expectedContains: []string{
				"Export canceled",
			},
		},
		{
			name:           "Export JSON to file (forced)",
			args:           []string{"export", "--force", "--format=json"},
			simulatedInput: testMasterPass + "\n",
			expectedContains: []string{
				"Vault exported to",
				"Secure the exported file",
			},
			verifyFile: true,
		},
		{
			name:           "Fails on unsupported format",
			args:           []string{"export", "--force", "--format=xml"},
			simulatedInput: testMasterPass + "\n",
			expectedError:  "unsupported export format: xml",
		},
		{
			name:           "Fails when vault is missing",
			args:           []string{"export", "--force"},
			simulatedInput: "",
			expectedError:  "vault file not found",
			missingVault:   true,
		},
	}
}

func TestExportCmd(t *testing.T) {
	const testMasterPass = "export_master_pass"
	tempDir := t.TempDir()
	tests := getExportCmdTestCases(testMasterPass)

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Clean Environment (No more global flags to reset!)
			viper.Reset()

			// Ensure absolute isolated path
			vaultName := "export_vault_" + strings.ReplaceAll(tt.name, " ", "_") + ".hako"
			testVaultPath := filepath.Clean(filepath.Join(tempDir, vaultName))

			// Fast crypto parameters
			viper.Set("argon2_iterations", 1)
			viper.Set("argon2_memory", 1024)
			viper.Set("argon2_parallelism", 1)

			// Setup Vault State using internal API
			if tt.missingVault {
				testVaultPath = filepath.Join(tempDir, "this_does_not_exist.vault")
			} else {
				// Use setupTestVault to init the file
				setupTestVault(t, testVaultPath, testMasterPass, []string{})

				// Inject edge-case entries for CSV/JSON testing manually
				func() {
					vf := storage.NewVaultFile(testVaultPath)
					masterBytes := []byte(testMasterPass)
					defer memory.SecureZero(masterBytes)

					vault, err := vf.Load(context.Background(), masterBytes, nil)
					require.NoError(t, err)

					// Entry 1: Standard entry
					pass1 := []byte("StandardPass123")
					defer memory.SecureZero(pass1)
					e1, err := secrets.NewEntry(
						"AppA",
						[]byte("admin"),
						pass1,
						[]byte("https://a.com"),
						[]byte("notes A"),
						[]string{"tag1"},
					)
					require.NoError(t, err)
					vault.AddEntry(e1)

					// Entry 2: Tricky entry with commas, quotes, and newlines
					pass2 := []byte("P@ss\"word\nLine2")
					defer memory.SecureZero(pass2)
					e2, err := secrets.NewEntry(
						"AppB",
						[]byte("user_name"),
						pass2,
						nil, // Empty URL
						[]byte("note,with,comma"),
						[]string{"tag2", "tag3"},
					)
					require.NoError(t, err)
					vault.AddEntry(e2)

					err = vf.Save(context.Background(), vault, masterBytes, nil)
					require.NoError(t, err)
				}()
			}

			// Prepare strict arguments
			cmdArgs := append([]string{}, tt.args...)
			cmdArgs = append(cmdArgs, "--vault="+testVaultPath, "--keyfile=none")

			// Dynamically inject --out parameter if verifying file
			outFileAbsPath := ""
			if tt.verifyFile {
				outFileAbsPath = filepath.Join(tempDir, "out_"+strings.ReplaceAll(tt.name, " ", "_")+".json")
				cmdArgs = append(cmdArgs, "--out="+outFileAbsPath)
			}

			// Execute target command with strictly mocked I/O
			actualOutput, err := executeCommandWithMocks(t, cmdArgs, tt.simulatedInput)

			// Assertions
			if tt.expectedError != "" {
				require.Error(t, err)
				assert.Contains(t, err.Error(), tt.expectedError)
				return
			}
			require.NoError(t, err)

			for _, expected := range tt.expectedContains {
				assert.Contains(t, actualOutput, expected)
			}

			// Assert File Output (if applicable)
			if tt.verifyFile {
				require.NotEmpty(t, outFileAbsPath, "Test is marked to verify file but no --out parameter was generated")

				// #nosec G304 -- Test file path is strictly controlled via t.TempDir() and filepath.Clean()
				fileData, readErr := os.ReadFile(filepath.Clean(outFileAbsPath))
				require.NoError(t, readErr, "Exported file should exist and be readable")
				fileContent := string(fileData)

				// Basic check to ensure the file is actually a JSON export of the vault
				assert.Contains(t, fileContent, `"name": "AppA"`)
				assert.Contains(t, fileContent, `"password": "StandardPass123"`)
			}
		})
	}
}

// -----------------------------------------------------------------------------
// Unit Tests (Internal Logic)
// -----------------------------------------------------------------------------

// TestWriteCSVField verifies the zero-allocation CSV RFC 4180 escaping logic.
// This assumes writeCSVField is defined in export.go (same package).
func TestWriteCSVField(t *testing.T) {
	tests := []struct {
		name     string
		input    []byte
		expected []byte
	}{
		{
			name:     "Empty field",
			input:    []byte(""),
			expected: []byte(""), // Should write nothing, but buffer might act differently
		},
		{
			name:     "Standard field",
			input:    []byte("hello world"),
			expected: []byte("hello world"),
		},
		{
			name:     "Field with comma",
			input:    []byte("hello,world"),
			expected: []byte(`"hello,world"`), // Wrapped in quotes
		},
		{
			name:     "Field with newlines",
			input:    []byte("line1\nline2\rline3"),
			expected: []byte(`"line1` + "\n" + `line2` + "\r" + `line3"`), // Wrapped in quotes
		},
		{
			name:     "Field with quotes",
			input:    []byte(`he said "hello" today`),
			expected: []byte(`"he said ""hello"" today"`), // Wrapped and inner quotes doubled
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var buf bytes.Buffer
			// writeCSVField is internal to package cli, so we can test it here
			err := writeCSVField(&buf, tt.input)
			require.NoError(t, err)

			if len(tt.expected) == 0 {
				assert.Empty(t, buf.Bytes())
			} else {
				assert.Equal(t, tt.expected, buf.Bytes())
			}
		})
	}
}
