package audit

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestNewLogger verifies the initialization of the logger.
func TestNewLogger(t *testing.T) {
	tmpDir := t.TempDir()
	logPath := filepath.Join(tmpDir, "audit.log")

	logger := NewLogger(logPath, true)
	assert.NotNil(t, logger)
	assert.Equal(t, logPath, logger.logPath)
	assert.True(t, logger.enabled)
	assert.NotEmpty(t, logger.sessionID)
	// Verify session format (either secure or fallback)
	assert.True(t, strings.HasPrefix(logger.sessionID, "sess_") || strings.HasPrefix(logger.sessionID, "fallback_"))
}

// TestLogEvent_EndToEnd verifies the complete logging lifecycle: Event -> JSON -> File.
func TestLogEvent_EndToEnd(t *testing.T) {
	tmpDir := t.TempDir()
	logPath := filepath.Join(tmpDir, "audit.log")
	logger := NewLogger(logPath, true)

	details := map[string]interface{}{
		"user": "testuser",
		"ip":   "192.168.1.1",
	}

	logger.LogEvent(EventVaultInit, true, "Vault initialized", details)

	// Verify file existence and permissions
	info, err := os.Stat(logPath)
	require.NoError(t, err)

	// On Unix, we expect strict 0600 (-rw-------).
	if os.PathSeparator == '/' {
		assert.Equal(t, os.FileMode(0600), info.Mode().Perm())
	}

	// Verify file content
	// #nosec G304 -- Trusted temporary path generated by t.TempDir() for testing purposes
	content, err := os.ReadFile(logPath)
	require.NoError(t, err)

	var event Event
	err = json.Unmarshal(content, &event)
	require.NoError(t, err)

	assert.Equal(t, EventVaultInit, event.EventType)
	assert.True(t, event.Success)
	assert.Equal(t, "Vault initialized", event.Message)
	assert.Equal(t, "testuser", event.Details["user"])
	assert.Equal(t, os.Getpid(), event.ProcessID)
	assert.Equal(t, logger.sessionID, event.SessionID)

	// Verify timestamp is recent (within 5 seconds)
	assert.WithinDuration(t, time.Now().UTC(), event.Timestamp, 5*time.Second)
}

// TestLogEvent_Disabled verifies that nothing is written when logger is disabled.
func TestLogEvent_Disabled(t *testing.T) {
	tmpDir := t.TempDir()
	logPath := filepath.Join(tmpDir, "audit.log")
	logger := NewLogger(logPath, false)

	logger.LogEvent(EventVaultInit, true, "Vault initialized", nil)

	_, err := os.Stat(logPath)
	assert.ErrorIs(t, err, os.ErrNotExist)
}

// TestSanitizeRecursive_Complex verifies the sanitization logic on complex structures.
// Since we are in 'package audit', we can test the private method sanitizeRecursive directly.
func TestSanitizeRecursive_Complex(t *testing.T) {
	logger := NewLogger("", true)

	// Struct for testing
	type UserStruct struct {
		Username string
		// #nosec G117 -- This is a test struct specifically designed to verify that the Password field is redacted
		Password string
		// #nosec G117 -- This is a test struct specifically designed to verify that the Secret field is redacted
		APISecret string
	}

	input := map[string]interface{}{
		"simple": "value",
		"nested": map[string]interface{}{
			"deep_secret": "my_secret_value",
			"safe":        "safe_value",
		},
		"struct_data": UserStruct{
			Username:  "admin",
			Password:  "supersecret",
			APISecret: "key123",
		},
		"ptr_data": &UserStruct{
			Username: "admin_ptr",
			Password: "ptr_secret",
		},
		"nil_ptr": (*UserStruct)(nil),
	}

	// Execution
	result := logger.sanitizeRecursive(input, 0)
	sanitized, ok := result.(map[string]interface{})
	require.True(t, ok, "Result should be a map")

	// Assertions
	assert.Equal(t, "value", sanitized["simple"])

	// Check Nested Map
	nested := sanitized["nested"].(map[string]interface{})
	assert.Equal(t, "[REDACTED]", nested["deep_secret"])
	assert.Equal(t, "safe_value", nested["safe"])

	// Check Struct flattening
	strData := sanitized["struct_data"].(map[string]interface{})
	assert.Equal(t, "admin", strData["Username"])
	assert.Equal(t, "[REDACTED]", strData["Password"])
	assert.Equal(t, "[REDACTED]", strData["APISecret"]) // Matches "secret"

	// Check Pointer
	ptrData := sanitized["ptr_data"].(map[string]interface{})
	assert.Equal(t, "admin_ptr", ptrData["Username"])
	assert.Equal(t, "[REDACTED]", ptrData["Password"])

	// Check Nil
	assert.Nil(t, sanitized["nil_ptr"])
}

// TestSanitize_Safety verifies that the logger does not panic on unsupported types.
func TestSanitize_Safety(t *testing.T) {
	logger := NewLogger("", true)

	// Function type (unsupported by JSON)
	myFunc := func() {}
	// Channel type (unsupported by JSON)
	myChan := make(chan int)
	// Float (supported)
	myFloat := 3.14
	// NaN (JSON does not support NaN, verify handling)
	myNaN := math.NaN()

	input := map[string]interface{}{
		"func_field": myFunc,
		"chan_field": myChan,
		"float":      myFloat,
		"nan":        myNaN,
	}

	result := logger.sanitizeRecursive(input, 0)
	sanitized := result.(map[string]interface{})

	// Assert fallback to string representation for unsupported types
	assert.Contains(t, sanitized["func_field"], "<type:func")
	assert.Contains(t, sanitized["chan_field"], "<type:chan")
	assert.Equal(t, 3.14, sanitized["float"])
	// Float64 is technically supported by reflect but handled by json.Marshal later.
	// sanitizeRecursive allows floats through.
	assert.True(t, math.IsNaN(sanitized["nan"].(float64)))
}

// TestSanitize_Limits verifies max depth and max string length.
func TestSanitize_Limits(t *testing.T) {
	logger := NewLogger("", true)

	// Test String Truncation
	longString := strings.Repeat("a", maxStringLength+100)
	inputStr := map[string]interface{}{
		"long": longString,
	}
	resStr := logger.sanitizeRecursive(inputStr, 0).(map[string]interface{})
	val := resStr["long"].(string)
	assert.True(t, len(val) < len(longString))
	assert.Contains(t, val, "[TRUNCATED]")

	// Test Max Depth
	// Create a deeply nested map manually
	deepMap := make(map[string]interface{})
	current := deepMap
	for i := 0; i < maxSanitizeDepth+5; i++ {
		next := make(map[string]interface{})
		current["next"] = next
		current = next
	}

	resDeep := logger.sanitizeRecursive(deepMap, 0)
	// We just want to ensure it didn't panic and returned something valid.
	// The recursion should have stopped at maxSanitizeDepth.
	assert.NotNil(t, resDeep)
}

// TestSanitize_SensitiveKeys verifies the case-insensitive redaction logic.
func TestSanitize_SensitiveKeys(t *testing.T) {
	logger := NewLogger("", true)

	tests := []struct {
		key            string
		expectedOutput string
	}{
		{"password", "[REDACTED]"},
		{"Password", "[REDACTED]"},
		{"USER_PASSWORD", "[REDACTED]"},
		{"api_key", "[REDACTED]"},
		{"my_secret_token", "[REDACTED]"},
		{"access_key_id", "[REDACTED]"},
		{"salt", "[REDACTED]"},
		{"username", "admin_value"},         // Should NOT be redacted
		{"public_key", "ssh-rsa-public..."}, // "public_key" does not match "private_key" strict matching (if applicable)
		{"my_public_key", "ssh-rsa-public..."},
	}

	for _, tt := range tests {
		t.Run(tt.key, func(t *testing.T) {
			// If we put "[REDACTED]" as input, the test passes even if the logger does nothing.
			rawInput := "SUPER_SENSITIVE_DATA"
			if tt.expectedOutput != "[REDACTED]" {
				rawInput = tt.expectedOutput
			}

			input := map[string]interface{}{tt.key: rawInput}
			res := logger.sanitizeRecursive(input, 0).(map[string]interface{})

			assert.Equal(t, tt.expectedOutput, res[tt.key], "Key '%s' was not sanitized correctly", tt.key)
		})
	}
}

// TestConcurrency verifies that the logger is thread-safe.
func TestConcurrency(t *testing.T) {
	tmpDir := t.TempDir()
	logPath := filepath.Join(tmpDir, "audit_concurrent.log")
	logger := NewLogger(logPath, true)

	var wg sync.WaitGroup
	routineCount := 50

	wg.Add(routineCount)
	for i := 0; i < routineCount; i++ {
		go func(id int) {
			defer wg.Done()
			logger.LogEvent(EventEntryGet, true, "Concurrent Access", map[string]interface{}{
				"id": id,
			})
		}(i)
	}

	wg.Wait()

	// Verify we have 50 lines in the file
	// #nosec G304 -- Trusted temporary path generated by t.TempDir()
	content, err := os.ReadFile(logPath)
	require.NoError(t, err)

	lines := strings.Split(strings.TrimSpace(string(content)), "\n")
	assert.Equal(t, routineCount, len(lines), "Should have exactly 50 log entries")

	// Verify last line is valid JSON
	var lastEvent Event
	err = json.Unmarshal([]byte(lines[len(lines)-1]), &lastEvent)
	require.NoError(t, err)
	assert.Equal(t, "Concurrent Access", lastEvent.Message)
}

// TestGlobalLogger verifies the singleton behavior.
// This test modifies global state, so it should not run in parallel with other tests
// that use the global logger.
func TestGlobalLogger(t *testing.T) {
	// Save current state to restore after test
	originalLogger := globalLogger
	defer func() {
		globalMu.Lock()
		globalLogger = originalLogger
		globalMu.Unlock()
	}()

	// Reset global logger to nil for this test
	globalMu.Lock()
	globalLogger = nil
	globalMu.Unlock()

	// Get uninitialized -> should return disabled logger (safe)
	logger := GetGlobalLogger()
	assert.NotNil(t, logger)
	assert.False(t, logger.enabled)
	assert.Equal(t, "", logger.logPath)

	// Initialize
	tmpDir := t.TempDir()
	logPath := filepath.Join(tmpDir, "global_audit.log")
	InitGlobalLogger(logPath, true)

	// Get initialized
	logger = GetGlobalLogger()
	assert.NotNil(t, logger)
	assert.True(t, logger.enabled)
	assert.Equal(t, logPath, logger.logPath)

	// Test helpers
	LogSuccess(EventVaultLoad, "Global Success", nil)
	LogFailure(EventAuthFailure, "Global Failure", nil)
	LogSecurityEvent("Global Security", nil)

	// Check file content
	// #nosec G304 -- Trusted temporary path generated by t.TempDir()
	content, err := os.ReadFile(logPath)
	require.NoError(t, err)
	lines := strings.Split(strings.TrimSpace(string(content)), "\n")
	assert.Equal(t, 3, len(lines))
}

func TestLogger_FastTailReader(t *testing.T) {
	tmpDir := t.TempDir()
	logPath := filepath.Join(tmpDir, "tail_test.log")

	// Empty file should return GenesisHash
	assert.Equal(t, GenesisHash, readLastHash(logPath))

	logger := NewLogger(logPath, true)
	logger.LogSuccess(EventVaultInit, "First event", nil)

	lastHash1 := logger.lastHash
	assert.NotEmpty(t, lastHash1)

	// Read last hash back using standalone readLastHash
	readHash := readLastHash(logPath)
	assert.Equal(t, lastHash1, readHash)

	// Add second event from a fresh logger instance (simulating short-lived CLI process)
	logger2 := NewLogger(logPath, true)
	logger2.LogSuccess(EventEntryAdd, "Second event", nil)

	// Verify that the second event's PrevHash was set to lastHash1
	content, err := os.ReadFile(logPath)
	require.NoError(t, err)
	lines := strings.Split(strings.TrimSpace(string(content)), "\n")
	require.Equal(t, 2, len(lines))

	var secondEvent Event
	err = json.Unmarshal([]byte(lines[1]), &secondEvent)
	require.NoError(t, err)
	assert.Equal(t, lastHash1, secondEvent.PrevHash, "Second event PrevHash must match first event Hash")
}

func TestLogger_Rotation(t *testing.T) {
	tmpDir := t.TempDir()
	logPath := filepath.Join(tmpDir, "rotate_test.log")

	// Max size 100 bytes, 2 backups, compression on
	logger := NewLoggerWithOptions(logPath, true, 100, 2, true, true)

	for i := 0; i < 5; i++ {
		logger.LogSuccess(EventEntryAdd, "Event message to test log rotation limit", map[string]interface{}{"i": i})
		time.Sleep(10 * time.Millisecond)
	}

	assert.FileExists(t, logPath)
	assert.FileExists(t, logPath+".1.gz")
}
